### ISSUE TITLE
关于Client和Server为什么不做成单例模式？

### ISSUE THREAD

**Issue by liewmanchoi** [songxinjianqwe/DistributedRPC#1]
您好，这几天正在学习您的项目，有一点疑惑，就是一台服务器上有可能部署多个服务，为什么这些服务不共享相同的底层网络设施，而是一个服务对应于一个`Client`/`Provider`实例？

**Comment by DYQiang** [comment]
您好,您代码中extensionLoader类会从toy文件夹下加载一些ProtocolConfig等各种Config对象，但是在sample-spring项目中，toy文件夹下只有一个Filter类，那这些Config类是咋样加载进去的呢？
